version: '2'
services:
  web:
    build: .
    ports:
      - 8000:5000
    volumes:
      - .:/code
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "hindustani.py"
    command: flask run --host=0.0.0.0